[unix_http_server]
file=/run/supervisord.sock

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
user=root
environment=HOME="/var/www/html"
umask=0002
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/bin/sh -c "nginx -g 'daemon off; pid /run/nginx/nginx.pid;'"
autorestart=true
startretries=5
user=www-data
stdout_logfile=/var/log/nginx/stdout.log
stderr_logfile=/var/log/nginx/stderr.log

[program:php-fpm]
command=php-fpm --nodaemonize
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:cron]
command=/usr/sbin/crond -f -l 8
autorestart=true
user=root
stdout_logfile=/var/log/cron/stdout.log
stderr_logfile=/var/log/cron/stderr.log
